### ISSUE TITLE
Feature request: back up RPC urls

### ISSUE THREAD

**Issue by jetstream0** [BananoCoin/bananojs#32]
Sometimes services like Kalium go down and it causes quite a few outages - to mitigate this I am proposing a way to designate a back up rpc should requests to the first rpc fail. Will try and implement myself when I have time, but opening this issue to remind myself and ask for discussion on the idea.

**Comment by coranos** [comment]
That sounds more like you want a proxy rather than a back up rpc url.

That being said, you can call setBananodeApi

https://github.com/BananoCoin/bananojs/blob/master/index.js#L26

and set it to a proxy, like the mock bananode

https://github.com/BananoCoin/bananojs/blob/master/test/util/mock-bananode-api.js

and then have your proxy do whatever you want.

If you plan on adding it to bananojs, bear in mind it needs 100% code coverage, which may be difficult depending on your error conditions and fail over complexity.

Alternately, you could just use a generic POST/GET proxy/load balancer.
